//
// Created by madjo on 09/01/2017.
//

#ifndef BINDINGOFJEANMICHEL_NEIGHBOURPOSITION_HPP
#define BINDINGOFJEANMICHEL_NEIGHBOURPOSITION_HPP
enum NeighBourPosition
{
    E_TOP,
    E_BOTTOM,
    E_LEFT,
    E_RIGHT
};
#endif //BINDINGOFJEANMICHEL_NEIGHBOURPOSITION_HPP
